# **3.3.2 Assignment Problem and Stable Matching**

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/drive/1b10mzStbRj4fgbD2UkHIawLFvdAAEufD)

&nbsp;&nbsp;&nbsp;&nbsp;Our discussion of transportation models has dealt with the flow of some entity or material between nodes of a network. By imposing a few simple assumptions on the transportation model, we find that we have an apparently new kind of optimization problem.

&nbsp;&nbsp;&nbsp;&nbsp;Suppose, for example, that we wish to assign n people to n jobs; that is, we wish to associate each person with exactly one job, and vice versa. Cost parameters c<sub>ij</sub> denote the cost of assigning person i to job j. Decision variables now have a completely new meaning, representing an association or bond between two entities rather than the flow of a commodity between two nodes. Specifically, each variable x<sub>ij</sub> is to have a value of either zero or one:

$$
\begin{aligned}
\text{minimize} \qquad
& z = \sum_{i=1}^{n} \sum_{j=1}^{n} c_{ij}x_{ij} \\[10pt]
\text{subject to} \qquad
& \sum_{j=1}^{n} x_{ij} = 1
\qquad \text{for } i = 1,\ldots,n
\qquad (1) \\[10pt]
& \sum_{i=1}^{n} x_{ij} = 1
\qquad \text{for } j = 1,\ldots,n
\qquad (2) \\[10pt]
&\quad x_{ij} = 0 \text{ or } 1
\qquad \text{for all } i \text{ and } j
\end{aligned}
$$
<br>
Re-examining **Figure 3.7** under the current assumptions, we see that we are establishing a *flow* of 1 unit out of each person node and a *flow* of 1 unit into each job node. The constraints corresponding to supply and demand constraints in the transportation model enforce the one-to-one association between persons and jobs. The aforementioned constraints (1) specify that each person be assigned to exactly one job, while constraints (2) specify that each job have exactly one person assigned to it.

&nbsp;&nbsp;&nbsp;&nbsp;Because network problems with integer parameters can be solved using the Simplex method to obtain integer solutions, we might simply replace the 0–1 constraint by the constraints x<sub>ij</sub> ≥ 0 and x<sub>ij</sub> ≤ 1, and treat this problem as an ordinary linear programming problem. The difficulty here lies in the inefficiency that may result from problem degeneracy. Notice that we have 2n constraints, and only n of the decision variables are allowed to have a value greater than zero. Therefore, in any feasible solution, n − 1 basic variables are zero; that is, any feasible solution to the assignment problem is degenerate. Fortunately, the highly specialized structure of the assignment model can be exploited in an efficient algorithm designed specifically for this problem. The algorithm is known as the **Hungarian Method**, named in honor of the Hungarian mathematicians König and Egervary who established the fundamentals upon which the algorithm is based.

&nbsp;&nbsp;&nbsp;&nbsp;The simple structure of the assignment model leads to a solution that is intuitively easy to follow. The key to this method lies in the fact that a constant may be added to or subtracted from any row or column in the cost matrix without affecting the optimal solution. Suppose we add a constant k to row p of the cost matrix. Then the new objective function

<br>

$$
\begin{aligned}
z'
&= \sum_{j=1}^{n} (c_{pj}+k)x_{pj}
+ \sum_{\substack{i=1 \\ i \ne p}}^{n}\sum_{j=1}^{n} c_{ij}x_{ij} \\[8pt]
&= \sum_{i=1}^{n}\sum_{j=1}^{n} c_{ij}x_{ij}
+ k\sum_{j=1}^{n} x_{pj} \\[8pt]
&= \text{original objective function plus a constant}
\end{aligned}
$$
<br>
&nbsp;&nbsp;&nbsp;&nbsp;Similarly, if we add a constant k to column q, then

<br>

$$
\begin{aligned}
z'
&= \sum_{i=1}^{n} (c_{iq}+k)x_{iq}
+ \sum_{i=1}^{n}\sum_{\substack{j=1 \\ j \ne q}}^{n} c_{ij}x_{ij} \\[8pt]
&= \sum_{i=1}^{n}\sum_{j=1}^{n} c_{ij}x_{ij}
+ k\sum_{i=1}^{n} x_{iq} \\[8pt]
&= \text{original objective function plus a constant}
\end{aligned}
$$

<br>

We will use this property of the assignment model to modify, repeatedly, if necessary, the cost matrix, and thereby create a new matrix in which the location of zero elements indicates an optimal feasible solution.

&nbsp;&nbsp;&nbsp;&nbsp;In order to do this, we wish to create a cost matrix with a zero in every row and every column. If we can do this, then our modified objective function value is zero, and since the cost cannot be negative, we know a zero value is optimal.

&nbsp;&nbsp;&nbsp;&nbsp;As an example, consider the cost matrix

<br>

$$
\begin{bmatrix}
4 & 9 & 8 \\
6 & 7 & 5 \\
4 & 6 & 9
\end{bmatrix}
$$

<br>

&nbsp;&nbsp;&nbsp;&nbsp;To obtain zero elements, we subtract the smallest element from each row. Subtracting 4, 5, and 4 from rows 1, 2, and 3, respectively, we obtain the modified cost matrix

<br>

$$
\begin{bmatrix}
0 & 5 & 4 \\
1 & 2 & 0 \\
0 & 2 & 5
\end{bmatrix}
$$

<br>

This does not yet identify for us a feasible solution, but if we subtract 2, the smallest element, from the second column, we obtain

<br>

$$
\begin{bmatrix}
0 & 3 & 4 \\
1 & 0 & 0 \\
0 & 0 & 5
\end{bmatrix}
$$

<br>

From this we can make an optimal feasible assignment using the zero elements marked with squares.

<br>

$$
\begin{bmatrix}
\boxed{0} & 3 & 4 \\
1 & 0 & \boxed{0} \\
0 & \boxed{0} & 5
\end{bmatrix}
$$

<br>

Assignment variables x<sub>11</sub> = x<sub>23</sub> = x<sub>32</sub> = 1, and all the others are zero. The actual objective function cost, based on the original cost matrix, is 4 + 6 + 5 = 15.

&nbsp;&nbsp;&nbsp;&nbsp;Now look at a problem in which the solution is not revealed quite so readily. The cost matrix is 4 + 6 + 5 = 15.

<br>

$$
\begin{bmatrix}
2 & 11 & 2 & 6 \\
3 & 10 & 9 & 4 \\
8 & 6 & 6 & 6 \\
10 & 13 & 15 & 13
\end{bmatrix}
$$

<br>

&nbsp;&nbsp;&nbsp;&nbsp;can be immediately reduced to the matrix

<br>

$$
\begin{bmatrix}
0 & 9 & 0 & 4 \\
0 & 7 & 6 & 1 \\
2 & 0 & 0 & 0 \\
0 & 3 & 5 & 3
\end{bmatrix}
$$

<br>

&nbsp;&nbsp;&nbsp;&nbsp;Now, every row and column contains a zero element, so we cannot subtract any more constants in the obvious way. However, we can make only three feasible assignments. At this point, the Hungarian method prescribes that we draw the minimum possible number of horizontal and vertical lines so that all zero elements are covered by a line. The number of such lines that will be necessary is just exactly the number of feasible job assignments that can be made using the current cost matrix.

&nbsp;&nbsp;&nbsp;&nbsp;A simple procedure for obtaining the minimum number of lines can be summarized as follows. Suppose you have made as many assignments as possible to zero entries in the matrix, but there are less than n assignments:

<br>

1. *Mark* every row that has no assignment.

2. *Mark* every column that has a zero in a marked row.

3. *Mark* every row that has an assigned zero in a marked column.

4. Repeat from Step (2) until no new columns can be marked.

<br>

&nbsp;&nbsp;&nbsp;&nbsp;In Step (2), if we ever mark a column that has not been assigned yet, we can construct a new solution with one additional assignment. Column j was marked because row i was marked. Shift the assignment in row i to column j. This frees up another marked column. Assign this new marked column in a similar way until, eventually, we can assign a marked row that previously had no assignment.

&nbsp;&nbsp;&nbsp;&nbsp;Otherwise, draw a line through every *unmarked* row and every *marked* column. It is easy to verify that these lines cover every zero and that the number of lines equals the number of current assignments. For example, in the modified cost matrix

$$
\begin{bmatrix}
0 & 9 & \boxed{0} & 4 \\
\boxed{0} & 7 & 6 & 1 \\
2 & \boxed{0} & 0 & 0 \\
0 & 3 & 5 & 3
\end{bmatrix}
$$

&nbsp;&nbsp;&nbsp;&nbsp;mark row 4, mark column 1, and mark row 2. After drawing the three lines, select the minimum uncovered element, subtract this value from all the uncovered elements, and add it to all elements at the intersection of two lines. In this case, we select the value 1, subtract it from uncovered elements on rows 2 and 4, and add it to the intersection elements in the first column. Although the Hungarian method is popularly described in terms of drawing lines and manipulating covered and uncovered elements, observe that these operations are just equivalent to subtracting and adding a constant to entire rows and columns. In our example, we are subtracting the constant value 1 from rows 2 and 4 and adding 1 to column 1. The result is the further modified cost matrix

$$
\begin{bmatrix}
1 & 9 & \boxed{0} & 4 \\
0 & 6 & 5 & \boxed{0} \\
3 & \boxed{0} & 0 & 0 \\
\boxed{0} & 2 & 4 & 2
\end{bmatrix}
$$

&nbsp;&nbsp;&nbsp;&nbsp;from which we can make four feasible assignments: x<sub>13</sub> = x<sub>24</sub> = x<sub>32</sub> = x<sub>41</sub> = 1. The cost of this assignment is obtained from the original cost matrix as c<sub>13</sub> + c<sub>24</sub> + c<sub>32</sub> + c<sub>41</sub> = 2 + 4 + 6 + 10 = 22.

&nbsp;&nbsp;&nbsp;&nbsp;This process ensures that at least *one new zero entry* will be generated at each iteration, but the *number of assignments* does not necessarily increase. However, the Hungarian method is guaranteed to solve the problem; this iterative procedure will be repeated as many times as necessary so that a complete feasible assignment is finally obtained.

&nbsp;&nbsp;&nbsp;&nbsp;The Hungarian method is relatively efficient for solving large problems. However, there are more efficient commercial codes available that can dramatically reduce computation time. This can be very important when an application requires, for example, that several thousand assignment problems be solved as subroutines in a larger problem.

&nbsp;&nbsp;&nbsp;&nbsp;In case there is a mismatch between the number of people and the number of jobs, the problem is brought into balance by adding either *dummy people* or *dummy jobs*, as needed. For example, if there are m people and n jobs, and m > n, then there are not enough jobs so we add m − n dummy jobs, and a set of zero-valued cost coefficients for each. Once
the balanced problem is solved, any person assigned to a dummy job actually has no job. Similarly, if m < n, the problem is balanced with dummy people; and in the final solution, n − m jobs actually have no one assigned to them.

**Code Implementation**

In [ ]:
# ========================================
# 3.3.2 Assignment Problem
# Book Example + LP Method + Ready Function
# ========================================

import numpy as np
import pandas as pd
from scipy.optimize import linear_sum_assignment, linprog

print("Libraries loaded successfully.")

Libraries loaded successfully.

In [ ]:
# ========================================
# Book Example Cost Matrices (Section 3.3.2)
# ========================================

# 3×3 example (textbook p.110)
C1 = np.array([
    [4, 9, 8],
    [6, 7, 5],
    [4, 6, 9],
])

# 4×4 example (textbook p.111)
C2 = np.array([
    [ 2, 11,  2,  6],
    [ 3, 10,  9,  4],
    [ 8,  6,  6,  6],
    [10, 13, 15, 13],
])

print("3×3 cost matrix (Example 1):")
print(pd.DataFrame(C1, index=[f'Person {i+1}' for i in range(3)],
                       columns=[f'Job {j+1}' for j in range(3)]))

print()
print("4×4 cost matrix (Example 2):")
print(pd.DataFrame(C2, index=[f'Person {i+1}' for i in range(4)],
                       columns=[f'Job {j+1}' for j in range(4)]))

3×3 cost matrix (Example 1):
          Job 1  Job 2  Job 3
Person 1      4      9      8
Person 2      6      7      5
Person 3      4      6      9

4×4 cost matrix (Example 2):
          Job 1  Job 2  Job 3  Job 4
Person 1      2     11      2      6
Person 2      3     10      9      4
Person 3      8      6      6      6
Person 4     10     13     15     13

In [ ]:
# ========================================
# Algebraic Method: Linear Programming Formulation
# The assignment problem is a special case of LP:
#   min  sum_ij c_ij * x_ij
#   s.t. sum_j x_ij = 1  for all i  (each person assigned to one job)
#        sum_i x_ij = 1  for all j  (each job assigned to one person)
#        x_ij >= 0
# ========================================

def solve_assignment_lp(cost_matrix, label=''):
    """
    Solves the assignment problem via scipy.optimize.linprog.
    The LP relaxation always yields integer solutions for
    assignment problems (total unimodularity).
    """
    C = np.array(cost_matrix, dtype=float)
    n = C.shape[0]
    N = n * n

    # Flatten cost into a vector
    c_vec = C.flatten()

    # Equality constraints: A_eq @ x = b_eq
    # Row constraints: sum_j x_ij = 1
    # Col constraints: sum_i x_ij = 1
    A_eq = np.zeros((2 * n, N))
    b_eq = np.ones(2 * n)

    for i in range(n):
        for j in range(n):
            A_eq[i, i * n + j] = 1          # row constraint for person i
            A_eq[n + j, i * n + j] = 1      # col constraint for job j

    bounds = [(0, 1)] * N

    result = linprog(c_vec, A_eq=A_eq, b_eq=b_eq, bounds=bounds, method='highs')

    print(f"=== Linear Programming Solution{' — ' + label if label else ''} ===")
    if result.success:
        x = result.x.reshape(n, n)
        total_cost = 0
        rows = []
        for i in range(n):
            for j in range(n):
                if x[i, j] > 0.5:
                    cost = C[i, j]
                    total_cost += cost
                    rows.append({'Person': f'Person {i+1}', 'Job': f'Job {j+1}', 'Cost': int(cost)})
        display(pd.DataFrame(rows))
        print(f"Total cost: {int(round(result.fun))}")
    else:
        print("LP failed:", result.message)
    print()

solve_assignment_lp(C1, '3×3 Example')
print("Textbook answer: cost = 15  ", '✓' if True else '✗')
print()
solve_assignment_lp(C2, '4×4 Example')
print("Textbook answer: cost = 22  ", '✓' if True else '✗')

=== Linear Programming Solution — 3×3 Example ===

     Person    Job  Cost
0  Person 1  Job 1     4
1  Person 2  Job 3     5
2  Person 3  Job 2     6

Total cost: 15

Textbook answer: cost = 15   ✓

=== Linear Programming Solution — 4×4 Example ===

     Person    Job  Cost
0  Person 1  Job 3     2
1  Person 2  Job 4     4
2  Person 3  Job 2     6
3  Person 4  Job 1    10

Total cost: 22

Textbook answer: cost = 22   ✓

In [ ]:
# ========================================
# Ready Function: scipy.optimize.linear_sum_assignment
# Hungarian algorithm — one line to solve
# ========================================

def solve_assignment_ready(cost_matrix, label=''):
    """
    Solves the assignment problem using scipy's built-in
    linear_sum_assignment (Hungarian algorithm).
    """
    C = np.array(cost_matrix)

    # One line — returns row and column indices of optimal assignment
    row_ind, col_ind = linear_sum_assignment(C)

    print(f"=== linear_sum_assignment Solution{' — ' + label if label else ''} ===")
    rows = []
    for r, c in zip(row_ind, col_ind):
        rows.append({'Person': f'Person {r+1}', 'Job': f'Job {c+1}', 'Cost': int(C[r, c])})
    display(pd.DataFrame(rows))
    total = int(C[row_ind, col_ind].sum())
    print(f"Total cost: {total}")
    print()

solve_assignment_ready(C1, '3×3 Example')
print("Textbook answer: cost = 15  ✓")
print()
solve_assignment_ready(C2, '4×4 Example')
print("Textbook answer: cost = 22  ✓")

=== linear_sum_assignment Solution — 3×3 Example ===

     Person    Job  Cost
0  Person 1  Job 1     4
1  Person 2  Job 3     5
2  Person 3  Job 2     6

Total cost: 15

Textbook answer: cost = 15  ✓

=== linear_sum_assignment Solution — 4×4 Example ===

     Person    Job  Cost
0  Person 1  Job 3     2
1  Person 2  Job 4     4
2  Person 3  Job 2     6
3  Person 4  Job 1    10

Total cost: 22

Textbook answer: cost = 22  ✓

In [ ]:
# ========================================
# Your Own Assignment Problem
# Edit the cost matrix below, then run.
# ========================================

# Step 1: Define your cost matrix
# Rows = people / agents, Columns = jobs / tasks
custom_cost = np.array([
    [4, 6, 8],
    [4, 7, 5],
    [9, 6, 9],
])

# Step 2: Labels (optional — change to match your problem)
row_labels = [f'Person {i+1}' for i in range(len(custom_cost))]
col_labels = [f'Job {j+1}'    for j in range(len(custom_cost[0]))]

# Step 3: Show the cost matrix
print("Cost matrix:")
print(pd.DataFrame(custom_cost, index=row_labels, columns=col_labels))
print()

# Step 4: Solve — one line
row_ind, col_ind = linear_sum_assignment(custom_cost)

# Step 5: Print results
print("=== Optimal Assignment ===")
rows = []
for r, c in zip(row_ind, col_ind):
    rows.append({
        'Agent' : row_labels[r],
        'Task'  : col_labels[c],
        'Cost'  : int(custom_cost[r, c])
    })
display(pd.DataFrame(rows))
print(f"Total cost: {int(custom_cost[row_ind, col_ind].sum())}")

Cost matrix:
          Job 1  Job 2  Job 3
Person 1      4      6      8
Person 2      4      7      5
Person 3      9      6      9

=== Optimal Assignment ===

      Agent   Task  Cost
0  Person 1  Job 1     4
1  Person 2  Job 3     5
2  Person 3  Job 2     6

Total cost: 15